# Generated by Django 4.1.5 on 2023-02-06 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeevalution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.BigIntegerField()),
                ('customer_score', models.BigIntegerField()),
                ('knowledge_score', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('deep_flag', models.CharField(max_length=10)),
                ('reason_deep', models.CharField(blank=True, max_length=1000, null=True)),
                ('exemplary_flag', models.CharField(max_length=10)),
                ('reason_exemplary', models.CharField(blank=True, max_length=1000, null=True)),
                ('additionalnote', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('case_number', models.BigIntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
